---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install tomcat
    yum: name=tomcat state=present
  - name: Start tomcat
    service: name=tomcat state=started
  - name: Deploy war file
    get_url: url=https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war dest=/usr/share/tomcat/webapps
    notify: restart tomcat
  handlers:
  - name: restart tomcat
    service: name=tomcat state=restarted

